name: Norminette CI

on:
  push:
    branches:
            - '*'

  pull_request:
    branches:
            - main

jobs:
  norminette_ci:
    name: Norminette Check
    runs-on: ubuntu-latest

    steps:
      - name: Clone Repo to Github
        uses: actions/checkout@v2

      - name: Set up Python for Norminette
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Set up Norminette
        run: |
            python3 -m pip install --upgrade pip
            pip install norminette

      - name: Run Norminette
        run: |
            norminette $(find . -type f -name '*.c' -o '*.h') > result.log || true
            grep 'Error' result.log || true

      - name: Error Check
        run: |
            if grep -q 'Error' result.log; then
              echo "❌ Norminette check failed!"
              exit 1
            else
              echo "✅ Norminette check passed!"
            fi
