name: Norminette CI

on:
  push:
    branches:
            - '*'

  pull_request:
    branches:
            - main

jobs :
  name: Norminette Check
  runs_on: ubuntu_latest

  steps:
    name: Clone Repo to Github
    uses: action/checkout@v2

    name: Set up Python for Norminette
    uses: action/setup-python@v2
    with:
      python-version: '3.8'

    name: Set up Norminette
    runs: |
        python3 -m pip install --upgrade pip
        pip install norminette

    name: Run Norminette
    runs: |
        norminette $(find . -type f -name '*.c' -o '*.h') > result.log || true
        grep  'ERROR' result.log || true

    name: Error Check
    runs: |
        if grep -q 'Error' result.log; then
          echo "❌ Norminette check failed!"
          exit 1
        else
          echo "✅ Norminette check passed!"
        fi
